### ISSUE TITLE
having problem upon pip install pcapy on python Python 3.10.6

### ISSUE THREAD

**Issue by wahyueko22** [xnih/satori#22]
pip install pcapy
Collecting pcapy
  Downloading pcapy-0.11.4.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\wahyu\AppData\Local\Temp\pip-install-29j01gm9\pcapy_a7a42d008a2c4d92910f9686c4457063\setup.py", line 49, in <module>
          save_init_posix = sysconfig._init_posix
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by wahyueko22** [comment]
On linux debian and linux version is Python 3.11.2 

pip3 install pcapy
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fwvuktq3/pcapy_7705fc90f21c4095b3105ad66e1c9984/setup.py", line 49, in <module>
          save_init_posix = sysconfig._init_posix
                            ^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xnih** [comment]
First, pcapy isn't anything I support, so this is just my thoughts on it, but not anything I can help a ton on.

1.
For windows, I've never had any luck getting pcapy installed, there should be a way to do it, but it requires some header files from what I recall to make it work.  On linux I bleieve these headers are part of libpcap-dev

2.
Installing it on ubuntu and redhat have been the primary linux builds I've done.  I'll try building a debian box later this week and check it out more.

----

You can try pcapyplus instead of pcapy, I got it setup to work instead of pcapy due to some oddities I ran into with pcapy on riscv and have continued to use pcapyplus on lots of my builds.  Code in satori will work with either pcapy or pcapyplus.

**Comment by xnih** [comment]
For Debian 12.5 use pcapyplus instead of pcapy.  Just verified it installs properly on Debian 12.5.
